<?php
	$this->slideshow_template = 'slideshow_basic.phtml';

	$this->links = array(
		new Link('Home', 'home', 'index.php'),
		new Link('Show page', 'show', 'show.php'),
		new Link('Videos page', 'videos', 'videos.php'),
		new Link('Reviews page', 'reviews', 'reviews.php'),
		new Link('Info page', 'info', 'info.php'),
		new Link('Contact page', 'contact', 'contact.php'),
	);
	
	$this->render('header.phtml');
?>

<body class="<?=$this->page_id?>">
<div id="page-container">

	<div id="header">
			
		<div id="logo" OnClick="document.location='index.php'">
			<noscript><a href="index.php"></noscript>
			<img src="resources/images/logo.png" width="800" height="125"/>
			<noscript></a></noscript>
		</div>
		
		<!-- Navigation links -->
		<div class="navigation" id="main_nav">
			<ul>
				<?php foreach ($this->links as $link): ?>
					<li id="<?=$link->style_id?>"><a href="<?=$link->link?>"><br><?=$link->name?></a></li>
				<?php endforeach; ?>
			</ul>
		</div>


		<div id="slideshow" class="slideshow">
			<?php foreach ($this->slides as $slide): ?>
				<img src="<?=$slide?>" width="800" height="300"/>
			<?php endforeach; ?>
		</div> <!-- End of slideshow -->
		
	</div> <!-- End of header -->
	
	<div id="content"> <!-- Content -->
		
			<div class="article transbox">
			<div class="padding">
				<h2><?=$this->content->title?></h2>
				<p><?=$this->content->summary1?></p>
				<?php if ($this->content->summary2): ?>
					<p><?=$this->content->summary2?></p>
				<?php endif; ?>
			</div></div>
	</div> <!-- End of Content -->
	
<?php
	$this->render('footer.phtml');
?>
