<?php
	$this->slideshow_template = 'slideshow_basic.phtml';

	$this->links = array(
		new Link('Home', 'home', 'index.php'),
		new Link('Show page', 'show', 'show.php'),
		new Link('Videos page', 'videos', 'videos.php'),
		new Link('Reviews page', 'reviews', 'reviews.php'),
		new Link('Info page', 'info', 'info.php'),
		new Link('Contact page', 'contact', 'contact.php'),
	);
	
	$this->render('header.phtml');
?>

<body class="<?=$this->page_id?>">
<div id="page-container">

	<div id="header">
			
		<div id="logo" OnClick="document.location='index.php'">
			<noscript><a href="index.php"></noscript>
			<img src="resources/images/logo.png" width="800" height="125"/>
			<noscript></a></noscript>
		</div>
		
		<!-- Navigation links -->
		<div class="navigation" id="main_nav">
			<ul>
				<?php foreach ($this->links as $link): ?>
					<li id="<?=$link->style_id?>"><a href="<?=$link->link?>"><br><?=$link->name?></a></li>
				<?php endforeach; ?>
			</ul>
		</div>


		<div id="slideshow" class="slideshow">
			<?php foreach ($this->slides as $slide): ?>
				<img src="<?=$slide?>" width="800" height="300"/>
			<?php endforeach; ?>
		</div> <!-- End of slideshow -->
		
	</div> <!-- End of header -->
	
	<div id="content"> <!-- Content -->
		
		<div class="article transbox">
		<div class="padding">
			<h2>Contact Page</h2><br>
			<table cellpadding="5">
				<tr><td>TITLE</td><td><b>Name</b></td><td>Contact number</td></tr>
				<tr><td> - </td><td><b> - </b></td><td> - </td></tr>
			</table>
		</div></div>
			
		<div class="article transbox">
		<div class="padding">
			<h2>Send us a message</h2><br>
			<form action="send_mail.php" method="post">
			<table>
				<tr>
					<td align="right">Your Email:</td>
					<td><input type="text" name="email_address" value="" maxlength="100" size="32" /></td>
					<td align="right">Send to:</td>
					<td>
						<select name="to_address">
							<option value="">send to</option>
						</select>
					</td>
					<td align="right"><input type="submit" value="Submit" disabled="disabled" style="background-color: darkgrey" /></td>
				</tr>
				<tr valign="top">
					<td align="right">Message:</td>
					<td colspan="4"><textarea rows="10" cols="50" name="comments" disabled="disabled" style="background-color: darkgrey">Text input disabled.</textarea></td>
				</tr>
			</table>
			</form>
		</div></div>
	</div> <!-- End of Content -->
	
<?php
	$this->render('footer.phtml');
?>
