<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
	<title><?=$this->title?></title>
	
	<meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
	<meta http-equiv="Content-Language" content="en-us" />
	<meta http-equiv="imagetoolbar" content="no" />
	
	<meta name="MSSmartTagsPreventParsing" content="true" />
	<meta name="description" content="Description" />
	<meta name="keywords" content="Keywords" />
	<meta name="author" content="Fradgers" />
	
	<link rel="stylesheet" href="css/master.css">
	<!-- <link rel="stylesheet" href="css/ie7.css"> -->

	<?php
		$this->render($this->slideshow_template);
	?>

</head>
