<?php
	$this->slideshow_template = 'slideshow_basic.phtml';

	$this->links = array(
		new Link('Home', 'home', 'index.php'),
		new Link('Show page', 'show', 'show.php'),
		new Link('Info page', 'info', 'info.php'),
		new Link('Contact page', 'contact', 'contact.php'),
	);
	
	$this->sublinks = array(
		new Link('Main', 'main', '#'),
		new Link('Testimonials', 'testimonials', '#'),
		new Link('Awards', 'awards', '#'),
		new Link('Clients', 'clients', '#'),
	);
	
	$this->render('header.phtml');
?>

<body class="<?=$this->page_id?>">
<div id="page-container">

	<div id="header">
	
		<!-- Navigation links -->
		<div id="main_nav">
			<?php foreach ($this->links as $link): ?>
				<div class="nav_button" id="<?=$link->style_id?>" 
					OnClick="document.location='<?=$link->link?>'"
				><?=$link->name?></div>
			<?php endforeach; ?>
		</div>
		
	</div> <!-- End of header -->
		
		<div id="slideshow" class="slideshow">
			<?php foreach ($this->slides as $slide): ?>
				<img src="<?=$slide?>" width="1000" height="300"/>
			<?php endforeach; ?>		
		</div> <!-- End of slideshow -->
		
		<div id="slideshow_overlay">
			<!--<iframe width="500" height="325" src="http://www.youtube.com/embed/adKlitJugeY?start=360" frameborder="0"></iframe>-->
			<!--<div id="words">
				<p>Words you can read.</p>
				<p style="display:none">Sdrow uoy nac daer.</p>
			</div>-->
		</div>

	
<?php
	$this->render('footer.phtml');
?>
