<?php
	$this->slideshow_template = 'slideshow_basic.phtml';

	$this->links = array(
		new Link('Home', 'home', 'index.php'),
		new Link('Show page', 'show', 'show.php'),
		new Link('Videos page', 'videos', 'videos.php'),
		new Link('Reviews page', 'reviews', 'reviews.php'),
		new Link('Info page', 'info', 'info.php'),
		new Link('Contact page', 'contact', 'contact.php'),
	);
	
	$this->render('header.phtml');
?>

<body class="<?=$this->page_id?>">
<div id="page-container">

	<div id="header">
			
		<div id="logo" OnClick="document.location='index.php'">
			<noscript><a href="index.php"></noscript>
			<img src="resources/images/logo.png" width="800" height="125"/>
			<noscript></a></noscript>
		</div>
		
		<!-- Navigation links -->
		<div class="navigation" id="main_nav">
			<ul>
				<?php foreach ($this->links as $link): ?>
					<li id="<?=$link->style_id?>"><a href="<?=$link->link?>"><br><?=$link->name?></a></li>
				<?php endforeach; ?>
			</ul>
		</div>


		<div id="slideshow" class="slideshow">
			<?php foreach ($this->slides as $slide): ?>
				<img src="<?=$slide?>" width="800" height="300"/>
			<?php endforeach; ?>
		</div> <!-- End of slideshow -->
		
	</div> <!-- End of header -->
	
	<div id="content"> <!-- Video filter controls -->
		
		<div class="article transbox">
		<div class="padding">
			<form action="reviews.php" method="get">
				<table cellpadding="3px">
					<tr>
						<td><h2>Review filter</h2></td>
						<td align="right">Show:</td>
						<td>
							<select name="show">
								<option value="">Any</option>
								<option value="soloist">The Soloist</option>
							</select>
						</td>
						<td align="right"><input type="submit" value="Go" /></td>
					</tr>
				</table>
			</form>
		</div></div>
	</div> <!-- End Video filter controls -->
	
	<div id="content"> <!-- Collection of show content -->
		
		<?php foreach ($this->contents as $content): ?>
			<div class="article transbox">
			<div class="padding">
				<table>
					<tr>

						<td valign="bottom">
							<h2><?=$content->title?></h2>
						</td>
					</tr>
					<tr>
						<td valign="top">
							<p><?=$content->summary1?></p>
						</td>
					</tr>
				</table>
			</div></div>
		<?php endforeach; ?>

		<!-- End of list of homepage articles -->
		
	</div> <!-- End of content -->
	
<?php
	$this->render('footer.phtml');
?>
