<?php
	$this->slideshow_template = 'slideshow_pager.phtml';

	$this->links = array(
		new Link('Home', 'home', 'index.php'),
		new Link('Show page', 'show', 'show.php'),
		new Link('Videos page', 'videos', 'videos.php'),
		new Link('Reviews page', 'reviews', 'reviews.php'),
		new Link('Info page', 'info', 'info.php'),
		new Link('Contact page', 'contact', 'contact.php'),
	);
	
	$this->sublinks = array(
		new Link('Home', 'home', 'index.php'),
		new Link('Show page', 'show', 'show.php'),
		new Link('Videos page', 'videos', 'videos.php'),
		new Link('Reviews page', 'reviews', 'reviews.php'),
	);
	
	
	$this->render('header.phtml');
?>

<body class="<?=$this->page_id?>">
<div id="page-container">

	<div id="header">
			
		<div id="logo" OnClick="document.location='index.php'">
			<noscript><a href="index.php"></noscript>
			<img src="resources/images/logo.png" width="1000" height="125"/>
			<noscript></a></noscript>
		</div>
		
		<!-- Navigation links -->
		<div class="navigation" id="main_nav">
			<?php foreach ($this->links as $link): ?>
				<div class="nav_button" id="<?=$link->style_id?>"
					OnClick="document.location='<?=$link->link?>'"
				><?=$link->name?></div>
			<?php endforeach; ?>
		</div>


		<div id="slideshow" class="slideshow">
			<?php foreach ($this->slides as $slide): ?>
				<img src="<?=$slide?>" width="1000" height="300"/>
			<?php endforeach; ?>
		</div> <!-- End of slideshow -->
		
	</div> <!-- End of header -->

<div id="content">

	<!-- Collection of show content -->
	<?php foreach ($this->contents as $content): ?>
		<div class="article transbox">
		<div class="padding">
			<h2><?=$content->title?></h2>
			<p><?=h($content->summary1)?></p>
			<?php if ($content->videogroup): ?>
				<!-- If the video list is marked as "flashonly", don't use html5 video tag,
					 just embed first video directly as flash -->
				<?php if ($content->videogroup->type == VIDEO_LINK): ?>
					<embed src="<?=$content->videogroup->videos->location?>" type="application/x-shockwave-flash" width="560" height="315" allowscriptaccess="always" allowfullscreen="true"></embed>
				<?php else: ?>
					<!-- Otherwise use html5 video tag as normal (use any flash urls as fallback) -->
					<video width="480" height="270" controls="controls" poster="resources/images/notredame_still.png">
					
					<?php foreach ($content->videogroup->videos as $video): ?>
						<?php if ($video->type != FLASH): ?>
							<source src="<?=$video->location?>" type="<?=$video->type?>" />
						<?php else: ?>
							<embed src="<?=$video->location?>" type="application/x-shockwave-flash" width="560" height="315" allowscriptaccess="always" allowfullscreen="true">
								Bad browser!
							</embed>
						<?php endif; ?>
					<?php endforeach; ?>
					
					</video>
				<?php endif; ?>
			<?php endif; ?>
			<?php if ($content->summary2): ?>
				<p><?=h($content->summary2)?></p>
			<?php endif; ?>
		</div></div>
	<?php endforeach; ?>

	<!-- End of list of homepage articles -->
	
</div> <!-- End of content -->
	
<?php
	$this->render('footer.phtml');
?>