
<!-- include jQuery library and Cycle slideshow plugin -->

	<link rel="stylesheet" href="css/my_jquery-ui.css" />
    
	<script src="scripts/jquery-1.8.2.js"></script>
	<script src="scripts/jquery-ui.js"></script>
	<script>
	$(function() {
		$( "#tabs" ).tabs();
	});
	
	function toggle_overlay_hide(currSlide, nextSlide, opts) {
		$( "#slideshow_overlay #words" ).toggle( "drop","slow" );
	};
	function toggle_overlay_show(currSlide, nextSlide, opts) {
		$( "#slideshow_overlay #words p" ).toggle();
		$( "#slideshow_overlay #words" ).toggle( "drop","slow" );
	};
	</script>

	<!-- Cycle slideshow settings -->
	<script type="text/javascript" src="scripts/jquery.cycle.all.latest.js"></script>
	<script type="text/javascript">
	$(document).ready(function() {
	$('.slideshow').cycle({
		before:	toggle_overlay_hide,
		after:	toggle_overlay_show,
		fx:     'fade',
		prev:   '#prev',
		next:   '#next',
		timeout: 5000,
		speed: 2000
	});
	});
	</script>
