<?php
	$this->slideshow_template = 'slideshow_basic.phtml';

	$this->links = array(
		new Link('Home', 'home', 'index.php'),
		new Link('Show page', 'show', 'show.php'),
		new Link('Videos page', 'videos', 'videos.php'),
		new Link('Reviews page', 'reviews', 'reviews.php'),
		new Link('Info page', 'info', 'info.php'),
		new Link('Contact page', 'contact', 'contact.php'),
	);
	
	$this->sublinks = array(
		new Link('Home', 'home', 'index.php'),
		new Link('Show page', 'show', 'show.php'),
		new Link('Videos page', 'videos', 'videos.php'),
		new Link('Reviews page', 'reviews', 'reviews.php'),
	);

	
	$this->render('header.phtml');
?>

<body class="<?=$this->page_id?>">
<div id="page-container">

	<div id="header">
			
		<div id="logo" OnClick="document.location='index.php'">
			<noscript><a href="index.php"></noscript>
			<img src="resources/images/logo.png" width="800" height="125"/>
			<noscript></a></noscript>
		</div>
		
		<!-- Navigation links -->
		<div class="navigation" id="main_nav">
			<?php foreach ($this->links as $link): ?>
				<div class="nav_button" id="<?=$link->style_id?>"
					OnClick="document.location='<?=$link->link?>'"
				><?=$link->name?></div>
			<?php endforeach; ?>
		</div>


		<div id="slideshow" class="slideshow">
			<?php foreach ($this->slides as $slide): ?>
				<img src="<?=$slide?>" width="1000" height="300"/>
			<?php endforeach; ?>
		</div> <!-- End of slideshow -->
		
		<div id=slideshow_overlay>
		<div id="buttons">
		<!-- List of homepage buttons -->
		<?php foreach ($this->articles as $article): ?>
			<div class="article"
				<?php if ($article->link): ?>
					OnClick="document.location='<?=$article->link?>'"
				<?php endif; ?>
			>
			<?php if ($article->link): ?>
				<noscript><a href="<?=$article->link?>"></noscript>
			<?php endif; ?>
				<?php if ($article->thumbnail): ?>
					<img src="<?=$article->thumbnail?>" alt="Thumbnail" />
				<?php endif; ?>
				<h2><a>
					<?=$article->title?>
				</a></h2>
				<p>
					<?=$article->summary?>
				</p>
				<?php if ($article->link): ?>
					<a>More...</a>
					<noscript></a></noscript>
				<?php endif; ?>
			</div>
		<?php endforeach; ?>
		</div> <!-- End of New Content -->
		</div>
		
		
	</div> <!-- End of header -->
	
	<div id="content"> <!-- Video filter controls -->
		
		<div class="article transbox">
		<div class="padding">
			<form action="videos.php" method="get">
				<table cellpadding="3px">
					<tr>
						<td><h2>Video filter</h2></td>
						<td align="right">Show:</td>
						<td>
							<select name="show">
								<option value="">Any</option>
								<option value="soloist">The Soloist</option>
								<option value="notredame">Notredame</option>
							</select>
						</td>
						<td align="right">Type:</td>
						<td>
							<select name="type">
								<option value="">Any</option>
								<option value="trailer">Trailer</option>
								<option value="rehearsal">Rehearsal</option>
								<option disabled="disabled" value="performance">Performance</option>
							</select>
						</td>
						<td align="right"><input type="submit" value="Go" /></td>
					</tr>
				</table>
			</form>
		</div></div>
	</div> <!-- End Video filter controls -->
	
	<div id="content"> <!-- Collection of show content -->
		
		<?php foreach ($this->contents as $content): ?>
			<div class="article transbox">
			<div class="padding">
				<table>
					<tr>
						<td rowspan="2">
							<!-- If the video list is marked as "flashonly", don't use html5 video tag,
								 just embed first video directly as flash -->
							<?php if ($content->videogroup->type == VIDEO_LINK): ?>
								<embed src="<?=$content->videogroup->videos->location?>" type="application/x-shockwave-flash" width="420" height="240" allowscriptaccess="always" allowfullscreen="true"></embed>
							<?php else: ?>
								<!-- Otherwise use html5 video tag as normal (use any flash urls as fallback) -->
								<video width="420" height="240" controls="controls" poster="resources/images/notredame_still.png">
								
								<?php foreach ($content->videogroup->videos as $video): ?>
									<?php if ($video->type != FLASH): ?>
										<source src="<?=$video->location?>" type="<?=$video->type?>" />
									<?php else: ?>
										<embed src="<?=$video->location?>" type="application/x-shockwave-flash" width="420" height="240" allowscriptaccess="always" allowfullscreen="true">
											Bad browser!
										</embed>
									<?php endif; ?>
								<?php endforeach; ?>
								
								</video>
							<?php endif; ?>
						</td>
						<td valign="bottom">
							<h2><?=$content->title?></h2>
						</td>
					</tr>
					<tr>
						<td valign="top">
							<p><?=$content->summary1?></p>
						</td>
					</tr>
				</table>
			</div></div>
		<?php endforeach; ?>

		<!-- End of list of homepage articles -->
		
	</div> <!-- End of content -->
	
<?php
	$this->render('footer.phtml');
?>
